# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojbMK4YR9l7Tx5c8H4HaLavY3yC4oVH9
"""



"""==========================================
FASE 3 - ÁRBOL DE DECISIÓN (REGRESIÓN)
Taller 1 - Sistemas Avanzados de Producción
==========================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# 1️ Cargar datos desde URL oficial
url = "https://raw.githubusercontent.com/selva86/datasets/master/Advertising.csv"
data = pd.read_csv(url)

# Seleccionar variables solicitadas
X = data [['TV', 'radio']]
y = data ['sales']

# 2️ División entrenamiento / prueba
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.3, random_state=42)

# 3️ Entrenar árbol de regresión
tree = DecisionTreeRegressor (max_depth=3, random_state=42) # profundidad controlada para evitar sobreajuste

tree.fit(X_train, y_train)

# 4️ Evaluación del modelo
y_pred = tree.predict(X_test)

print ("R2 en prueba:", round(r2_score(y_test, y_pred), 4))
print ("MSE en prueba:", round(mean_squared_error(y_test, y_pred), 4))

# 5️ Importancia de variables
importance = pd.DataFrame ({ "Variable": X.columns, "Importancia": tree.feature_importances_})

print("\nImportancia de Variables:")
print(importance.sort_values(by="Importancia", ascending=False))

# 6️ Graficar el árbol
plt.figure(figsize=(20,10))
plot_tree(tree, feature_names=X.columns, filled=True, rounded=True, fontsize=10)

plt.title("Árbol de Regresión - Predicción de Sales")
plt.show()