# -*- coding: utf-8 -*-
"""Copia de Fase 2: Optimización Numérica y Descenso de Gradiente

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScwVGyG9enTwREYCr4hwvRzQmQeFdaz6

## Experimento 2: Tasa de aprendizaje alta
"""

# -*- coding: utf-8 -*-
# Paso 1: Importar las librerías necesarias
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Paso 2: Definir la función y su gradiente
# Esta función tiene múltiples mínimos locales para que el algoritmo pueda "atascarse"
def f(x, y):
    """Función de superficie con dos mínimos locales."""
    return (x**2 + y - 11)**2 + (x + y**2 - 7)**2

def grad_f(x, y):
    """Gradiente (derivadas parciales) de la función f."""
    df_dx = 2 * (x**2 + y - 11) * (2*x) + 2 * (x + y**2 - 7)
    df_dy = 2 * (x**2 + y - 11) + 2 * (x + y**2 - 7) * (2*y)
    return np.array([df_dx, df_dy])

# Paso 3: Implementar el algoritmo de Descenso del Gradiente
def gradient_descent(start_pos, learning_rate, num_iterations):
    """
    Ejecuta el descenso del gradiente y guarda la trayectoria.

    Args:
        start_pos (np.array): Punto de inicio [x, y].
        learning_rate (float): Tasa de aprendizaje (tamaño del paso).
        num_iterations (int): Número de pasos a realizar.

    Returns:
        np.array: Un array con la trayectoria de los puntos (x, y, z).
    """
    path = []
    point = np.array(start_pos, dtype=float)

    for i in range(num_iterations):
        z = f(point[0], point[1])
        path.append([point[0], point[1], z])

        # Calcula el gradiente
        grad = grad_f(point[0], point[1])

        # Actualiza la posición del punto
        point = point - learning_rate * grad

    return np.array(path)

# --- CONFIGURACIÓN DE LA SIMULACIÓN ---
# Punto de inicio (puedes cambiarlo para ver cómo cae en otro mínimo)
start_point = [0.0, 0.1]
learning_rate = 0.0001      # Tasa de aprendizaje
num_iterations = 1000       # Número de pasos

# Ejecutar el algoritmo
path = gradient_descent(start_point, learning_rate, num_iterations)

# --- PREPARACIÓN DE LA VISUALIZACIÓN ---
# Crear la malla de puntos para la superficie 3D y las curvas de nivel
x = np.linspace(-7, 7, 200)
y = np.linspace(-7, 7, 200)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Crear la figura y los dos subplots (3D y 2D)
fig = plt.figure(figsize=(15, 7))
ax1 = fig.add_subplot(1, 2, 1, projection='3d')
ax2 = fig.add_subplot(1, 2, 2)

# --- DIBUJO DE LA SUPERFICIE Y LAS CURVAS DE NIVEL ---

# Subplot 1: Superficie 3D
ax1.plot_surface(X, Y, Z, cmap='viridis', alpha=0.6, rstride=10, cstride=10, edgecolor='none')
ax1.set_title('Descenso del Gradiente en 3D', fontsize=16)
ax1.set_xlabel('X')
ax1.set_ylabel('Y')
ax1.set_zlabel('f(x, y)')
ax1.view_init(elev=50, azim=-70) # Ajustar el ángulo de la vista 3D

# Subplot 2: Proyección en curvas de nivel
contour = ax2.contour(X, Y, Z, levels=np.logspace(0, 5, 35), cmap='viridis', alpha=0.8)
fig.colorbar(contour, ax=ax2, label='Valor de f(x,y)')
ax2.set_title('Proyección en Curvas de Nivel', fontsize=16)
ax2.set_xlabel('X')
ax2.set_ylabel('Y')
ax2.set_aspect('equal', adjustable='box')

# Elementos que se animarán
line_3d, = ax1.plot([], [], [], 'r-o', markersize=4, lw=2, label='Trayectoria')
point_3d, = ax1.plot([], [], [], 'go', markersize=8, label='Punto Actual')
line_2d, = ax2.plot([], [], 'r-o', markersize=4, lw=2)
point_2d, = ax2.plot([], [], 'go', markersize=8)

ax1.legend()

# --- FUNCIÓN DE ANIMACIÓN ---
def update(frame):
    # Actualiza los datos de las líneas y puntos hasta el frame actual
    line_3d.set_data(path[:frame, 0], path[:frame, 1])
    line_3d.set_3d_properties(path[:frame, 2])
    point_3d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])
    point_3d.set_3d_properties(path[frame:frame+1, 2])

    line_2d.set_data(path[:frame, 0], path[:frame, 1])
    point_2d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])

    return line_3d, point_3d, line_2d, point_2d

# Crear y mostrar la animación
ani = FuncAnimation(fig, update, frames=len(path), blit=True, interval=20)

# Convertir la animación a un formato compatible con Colab (HTML5)
plt.close(fig) # Evita que se muestre una figura estática extra
HTML(ani.to_html5_video())

# --- CONFIGURACIÓN DE LA SIMULACIÓN ---
# Punto de inicio (puedes cambiarlo para ver cómo cae en otro mínimo)
start_point = [0.0, 0.1]
learning_rate = 0.5    # Tasa de aprendizaje
num_iterations = 1000       # Número de pasos

# Ejecutar el algoritmo
path = gradient_descent(start_point, learning_rate, num_iterations)

# --- PREPARACIÓN DE LA VISUALIZACIÓN ---
# Crear la malla de puntos para la superficie 3D y las curvas de nivel
x = np.linspace(-7, 7, 200)
y = np.linspace(-7, 7, 200)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Crear la figura y los dos subplots (3D y 2D)
fig = plt.figure(figsize=(15, 7))
ax1 = fig.add_subplot(1, 2, 1, projection='3d')
ax2 = fig.add_subplot(1, 2, 2)

# --- DIBUJO DE LA SUPERFICIE Y LAS CURVAS DE NIVEL ---

# Subplot 1: Superficie 3D
ax1.plot_surface(X, Y, Z, cmap='viridis', alpha=0.6, rstride=10, cstride=10, edgecolor='none')
ax1.set_title('Descenso del Gradiente en 3D', fontsize=16)
ax1.set_xlabel('X')
ax1.set_ylabel('Y')
ax1.set_zlabel('f(x, y)')
ax1.view_init(elev=50, azim=-70) # Ajustar el ángulo de la vista 3D

# Subplot 2: Proyección en curvas de nivel
contour = ax2.contour(X, Y, Z, levels=np.logspace(0, 5, 35), cmap='viridis', alpha=0.8)
fig.colorbar(contour, ax=ax2, label='Valor de f(x,y)')
ax2.set_title('Proyección en Curvas de Nivel', fontsize=16)
ax2.set_xlabel('X')
ax2.set_ylabel('Y')
ax2.set_aspect('equal', adjustable='box')

# Elementos que se animarán
line_3d, = ax1.plot([], [], [], 'r-o', markersize=4, lw=2, label='Trayectoria')
point_3d, = ax1.plot([], [], [], 'go', markersize=8, label='Punto Actual')
line_2d, = ax2.plot([], [], 'r-o', markersize=4, lw=2)
point_2d, = ax2.plot([], [], 'go', markersize=8)

ax1.legend()

# --- FUNCIÓN DE ANIMACIÓN ---
def update(frame):
    # Actualiza los datos de las líneas y puntos hasta el frame actual
    line_3d.set_data(path[:frame, 0], path[:frame, 1])
    line_3d.set_3d_properties(path[:frame, 2])
    point_3d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])
    point_3d.set_3d_properties(path[frame:frame+1, 2])

    line_2d.set_data(path[:frame, 0], path[:frame, 1])
    point_2d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])

    return line_3d, point_3d, line_2d, point_2d

# Crear y mostrar la animación
ani = FuncAnimation(fig, update, frames=len(path), blit=True, interval=20)

# Convertir la animación a un formato compatible con Colab (HTML5)
plt.close(fig) # Evita que se muestre una figura estática extra
HTML(ani.to_html5_video())

# --- CONFIGURACIÓN DE LA SIMULACIÓN ---
# Punto de inicio (puedes cambiarlo para ver cómo cae en otro mínimo)
start_point = [0.0, 0.1]
learning_rate = 1e-7    # Tasa de aprendizaje
num_iterations = 1000       # Número de pasos

# Ejecutar el algoritmo
path = gradient_descent(start_point, learning_rate, num_iterations)

# --- PREPARACIÓN DE LA VISUALIZACIÓN ---
# Crear la malla de puntos para la superficie 3D y las curvas de nivel
x = np.linspace(-7, 7, 200)
y = np.linspace(-7, 7, 200)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Crear la figura y los dos subplots (3D y 2D)
fig = plt.figure(figsize=(15, 7))
ax1 = fig.add_subplot(1, 2, 1, projection='3d')
ax2 = fig.add_subplot(1, 2, 2)

# --- DIBUJO DE LA SUPERFICIE Y LAS CURVAS DE NIVEL ---

# Subplot 1: Superficie 3D
ax1.plot_surface(X, Y, Z, cmap='viridis', alpha=0.6, rstride=10, cstride=10, edgecolor='none')
ax1.set_title('Descenso del Gradiente en 3D', fontsize=16)
ax1.set_xlabel('X')
ax1.set_ylabel('Y')
ax1.set_zlabel('f(x, y)')
ax1.view_init(elev=50, azim=-70) # Ajustar el ángulo de la vista 3D

# Subplot 2: Proyección en curvas de nivel
contour = ax2.contour(X, Y, Z, levels=np.logspace(0, 5, 35), cmap='viridis', alpha=0.8)
fig.colorbar(contour, ax=ax2, label='Valor de f(x,y)')
ax2.set_title('Proyección en Curvas de Nivel', fontsize=16)
ax2.set_xlabel('X')
ax2.set_ylabel('Y')
ax2.set_aspect('equal', adjustable='box')

# Elementos que se animarán
line_3d, = ax1.plot([], [], [], 'r-o', markersize=4, lw=2, label='Trayectoria')
point_3d, = ax1.plot([], [], [], 'go', markersize=8, label='Punto Actual')
line_2d, = ax2.plot([], [], 'r-o', markersize=4, lw=2)
point_2d, = ax2.plot([], [], 'go', markersize=8)

ax1.legend()

# --- FUNCIÓN DE ANIMACIÓN ---
def update(frame):
    # Actualiza los datos de las líneas y puntos hasta el frame actual
    line_3d.set_data(path[:frame, 0], path[:frame, 1])
    line_3d.set_3d_properties(path[:frame, 2])
    point_3d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])
    point_3d.set_3d_properties(path[frame:frame+1, 2])

    line_2d.set_data(path[:frame, 0], path[:frame, 1])
    point_2d.set_data(path[frame:frame+1, 0], path[frame:frame+1, 1])

    return line_3d, point_3d, line_2d, point_2d

# Crear y mostrar la animación
ani = FuncAnimation(fig, update, frames=len(path), blit=True, interval=20)

# Convertir la animación a un formato compatible con Colab (HTML5)
plt.close(fig) # Evita que se muestre una figura estática extra
HTML(ani.to_html5_video())